name: Candidate CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'service-b/**'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Building b service"

  package:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Packaging b service"

  deploy:
    needs: package
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying b service"